### ISSUE TITLE
can not builld 

### ISSUE THREAD

**Issue by jianwk** [coderplay/perfj#3]
$ gradle releaseTarGz

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'perfj'.
  
  > Cannot add Mutate rule 'org.gradle.language.base.plugins.ComponentModelBasePlugin$Rules#closeSourcesForBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.language.base.ProjectSourceSet)' for model element 'binaries' when element is in state GraphClosed.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by coderplay** [comment]
Gradle 2.4 has a bug on c plugin. I've update the building steps to avoid using gradle 2.4 .
