### ISSUE TITLE
After the build, I ran the "bin/perfj record " cmd and got some exception

### ISSUE THREAD

**Issue by zbhuang** [coderplay/perfj#4]
Hi, I tried to run the cmd of "bin/perfj record -e sched:sched_switch -F 99 -g -p `pgrep -f ContextSwitchTest` sleep 5", but got the following exception, which I could not figure it out.
(In my ubuntu14.04.2 x64, I only have one java, which is that jdk8u60 early release version and perf is also installed successfully.)
Did I miss anything ? or could you give me some hint ?

zbhuang@ubuntu:~/Downloads/perfj$ bin/perfj record -e sched:sched_switch -F 99 -g -p `pgrep -f ContextSwitchTest` sleep 5
Exception in thread "main" com.sun.tools.attach.AttachNotSupportedException: Invalid process identifier
    at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:66)
    at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
    at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
    at info.minzhou.perfj.PerfJ.loadAgent(PerfJ.java:223)
    at info.minzhou.perfj.PerfJ.main(PerfJ.java:238)
chown: cannot access ‘./tmp/perf-sleep.map’: No such file or directory

Before reaching this exception, I have to make some changes below, which might help you update your README.md (to be more user friendly).
1) add "PERFJ_HOME" into /etc/profile
2) in bin/perfj, change "-maxdepth 1" to "-maxdepth 3", otherwise, perfj-*.jar will not be found out.
3) it is better to provide your test java file, ContextSwitchTest.java, but anyway, I found it here, http://coderplay.iteye.com/blog/1481211

**Comment by zbhuang** [comment]
Hi, after reading README.md many times and re-tested it, now I understand it - right after running this cmd, "java -XX:+PreserveFramePointer ContextSwitchTest", I have to open another console to run the other cmd, bin/perfj record -e sched:sched_switch -F 99 -g -p `pgrep -f ContextSwitchTest` sleep 5.
Got it, thanks !

**Comment by coderplay** [comment]
Thank your for your advise. Actually, I am thinking about making a debian/rpm distribution, so that users can run perfj as easy as other linux commands.
